### ISSUE TITLE
POST istället för PUT

### ISSUE THREAD

**Issue by Jarleborn** [Angamanga/1dv450-ki222bj#5]
Du använder POST för att uppdatera. Så som jag förstår det så borde du använda PUT istället då det enligt specificationen är mer korrekt. John har två bra slides som förklara dessa två 
![slide 1](https://cloud.githubusercontent.com/assets/8629702/14659610/e110b9e6-069d-11e6-883d-a2704083b239.PNG)
![slide 2](https://cloud.githubusercontent.com/assets/8629702/14659609/e10e93dc-069d-11e6-89ee-702f2177b560.PNG)

**Comment by Jarleborn** [comment]
Bör dock tilläggas att det fungerar felfritt att uppdatera en resurs

**Comment by Angamanga** [comment]
Japp. Helt sant!
